# Generated by Django 5.2.9 on 2025-12-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_category_note_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_html',
            field=models.BooleanField(default=False, verbose_name='HTML 코드 적용'),
        ),
    ]
